name: Build Latex Paper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    container: blang/latex
    steps:
    - uses: actions/checkout@v2
    - name: Build paper
      run: (cd papers/dyplom && ./build.sh)
    - name: Grant execute permission for gradlew
      run: chmod +x ./BreedKN/gradlew
    - name: Upload Paper
      uses: actions/upload-artifact@v1
      with:
        name: paper
        path: papers/dyplom/dyplom.pdf
