name: Build Latex Paper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: sigan/latex
    steps:
    - uses: actions/checkout@v2
    - name: Build paper
      run: (cd papers/dyplom && ./build_paper.sh)
    - name: Upload Paper
      uses: actions/upload-artifact@v1
      with:
        name: paper
        path: papers/dyplom/dyplom.pdf
