name: Build Latex Paper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_rn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm ci

  build_dyplom_paper:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: aergus/latex
    steps:
    - uses: actions/checkout@v2
    - name: Build paper
      run: (cd papers/dyplom && ./build.sh)
    - name: Upload Paper
      uses: actions/upload-artifact@v1
      with:
        name: paper
        path: papers/dyplom/dyplom.pdf
