name: Build Latex Paper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_rn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1
    - name: Install node modules
      run: |
        npm ci
  build_dyplom_paper:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: aergus/latex
    steps:
    - uses: actions/checkout@v2
    - name: Build paper
      run: (cd papers/dyplom && ./build.sh)
    - name: Upload Paper
      uses: actions/upload-artifact@v1
      with:
        name: paper
        path: papers/dyplom/dyplom.pdf
